### ISSUE TITLE
Edumeet Management UI

### ISSUE THREAD

**Issue by rAbdelHadi** [edumeet/edumeet-management-server#1]
Hey , 

Is there any management UI for this server or I have to build my own UI for it? 

Many thanks

**Comment by N7Remus** [comment]
Hi,

At the moment it is very basic : https://github.com/edumeet/edumeet-management-client

**Comment by N7Remus** [comment]
It should be stable enough now, please check out the edumeet-client repo or edumeet-docker repo 4.x / main branch for easy setup.
